/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2022-04-11 16:30:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.servlet.http.HttpSession;

public final class userhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/db.jsp", Long.valueOf(1645982071421L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Class.forName("com.mysql.jdbc.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Medicare","root","1607");

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String userName = (String)session.getAttribute("username"); 
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./assets/logo$.png\" type=\"image/icon type\">\r\n");
      out.write("    <!-- CSS only -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We\" crossorigin=\"anonymous\">\r\n");
      out.write("    <!-- icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\"\r\n");
      out.write("        integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" crossorigin=\"anonymous\" />\r\n");
      out.write("    <title>Medicare</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: rgb(253, 247, 247); font-family: 'Satisfy', cursive; overflow-x: hidden;\">\r\n");
      out.write("    \r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-md rounded d-flex justify-content-between\">\r\n");
      out.write("            <div style=\"height:70px; width: 120px;\">\r\n");
      out.write("                <div style=\"width: 100%; height: 100%;\">\r\n");
      out.write("                    <img src=\"./assets/Logo (2).png\" alt=\"logo\" style=\"width:100%; height: 100%; background-size: 200% auto;\" class=\"rounded\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d-flex flex-row justify-content-between\">\r\n");
      out.write("                <div style=\"align-items: center; padding: 10px;\">\r\n");
      out.write("                    <a class=\" text-white\" href=\"Profile.html\" style=\"margin: 10px;\">\r\n");
      out.write("                        ");
      out.print(userName );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a class=\"btn button-outline-none text-white m-1\" href=\"Signout\">\r\n");
      out.write("                        sign out\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"conatiner m-5\">\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t");

	
	/*String qr1 = "select location from user where userName=?";
	PreparedStatement ps1 = con.prepareStatement(qr1);
	ps1.setString(1, userName);
	ResultSet rs1 = ps1.executeQuery();
	if(rs.next())
	 {
		 do{
			 String location=rs.getString("location");
			 String loc[] = location.split(", ");
			 
			 String lon = loc[0];
			 String lat = loc[1];
			 
		 }while(rs.next());
	
	*/
	String qr = "select * from medFac";
	
	PreparedStatement ps = con.prepareStatement(qr);
	
	ResultSet rs = ps.executeQuery();
	 if(rs.next())
	 {
		 do{
			 String cname = rs.getString("clinicName");
			 String img = rs.getString("img");
			 String add = rs.getString("address");
			 String id = rs.getString("id");
			 String time = rs.getString("time");
			 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t            <div class=\" col-3 gap-5 mt-4\">\r\n");
      out.write("\t                <div class=\"card\">\r\n");
      out.write("\t                    <div class=\"card-body\">\r\n");
      out.write("\t                      <h5 class=\"card-title\">");
      out.print(cname);
      out.write("</h5>\r\n");
      out.write("\t                      <img style=\"height: 200px\" class=\"card-img-top\" ");
out.println("src=./images/"+img) ;
      out.write(" alt=\"Card image cap\">\r\n");
      out.write("\t                      <p class=\"card-text\">\r\n");
      out.write("\t                      \t");
      out.print(add );
      out.write("<br>\r\n");
      out.write("\t                      \tfrom: ");
      out.print(time );
      out.write("\r\n");
      out.write("\t                      </p>\r\n");
      out.write("\t                      <a ");
out.println("href=page.jsp?id="+id); 
      out.write(" class=\"btn text-white\">Go to clinic</a>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t ");
 
		 }while(rs.next());
	 }else{
		 out.println("No data found....");
	 }
	
	
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
